# Generated by Django 2.1.7 on 2019-04-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_column='Nombre', max_length=50)),
                ('apellido', models.TextField(db_column='Apellido', max_length=45)),
                ('direccion', models.TextField(db_column='Direccion', max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'Asociado',
            },
        ),
    ]
